In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
from pathlib import Path

# 원본 데이터 루트
DATA_ROOT = Path(
    "/content/drive/MyDrive/빅프/"
    "081_스마트야드_압축해제/"
    "3.개방데이터/1.데이터"
)

# 원본을 건드리지 않고 분석 결과만 저장할 폴더
WORK_ROOT = Path(
    "/content/drive/MyDrive/빅프/"
    "shared_backbone_workspace"
)

REPORT_ROOT = WORK_ROOT / "reports"
MANIFEST_ROOT = WORK_ROOT / "manifests"
VIS_ROOT = WORK_ROOT / "visualizations"

for path in [REPORT_ROOT, MANIFEST_ROOT, VIS_ROOT]:
    path.mkdir(parents=True, exist_ok=True)

print("DATA_ROOT:", DATA_ROOT)
print("WORK_ROOT:", WORK_ROOT)
print("DATA_ROOT exists:", DATA_ROOT.exists())

assert DATA_ROOT.exists(), f"데이터 루트를 찾을 수 없습니다: {DATA_ROOT}"

DATA_ROOT: /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터
WORK_ROOT: /content/drive/MyDrive/빅프/shared_backbone_workspace
DATA_ROOT exists: True

In [3]:
def print_tree(root: Path, max_depth: int = 3):
    root = root.resolve()
    print(root.name)

    for path in sorted(root.rglob("*")):
        try:
            depth = len(path.relative_to(root).parts)
        except ValueError:
            continue

        if depth > max_depth:
            continue

        indent = "    " * depth
        suffix = "/" if path.is_dir() else ""
        print(f"{indent}{path.name}{suffix}")


print_tree(DATA_ROOT, max_depth=3)

1.데이터
    Training/
        01.원천데이터/
            TS_안전장비-S63_DATA3_안전대미착용-B0/
            TS_안전장비-S63_DATA3_안전대미착용-B0.zip
            TS_안전장비-S63_DATA3_안전대착용-B1/
            TS_안전장비-S63_DATA3_안전대착용-B1.zip
            TS_안전장비-S63_DATA3_안전모미착용-H0/
            TS_안전장비-S63_DATA3_안전모미착용-H0.zip
            TS_안전장비-S63_DATA3_안전모착용-H1/
            TS_안전장비-S63_DATA3_안전모착용-H1.zip
            TS_안전장비-S63_DATA3_용접마스크미착용-M0/
            TS_안전장비-S63_DATA3_용접마스크미착용-M0.zip
            TS_안전장비-S63_DATA3_용접마스크착용-M1/
            TS_안전장비-S63_DATA3_용접마스크착용-M1.zip
        02.라벨링데이터/
            TL_안전장비-S63_DATA3_안전대미착용-B0/
            TL_안전장비-S63_DATA3_안전대미착용-B0.zip
            TL_안전장비-S63_DATA3_안전대착용-B1/
            TL_안전장비-S63_DATA3_안전대착용-B1.zip
            TL_안전장비-S63_DATA3_안전모미착용-H0/
            TL_안전장비-S63_DATA3_안전모미착용-H0.zip
            TL_안전장비-S63_DATA3_안전모착용-H1/
            TL_안전장비-S63_DATA3_안전모착용-H1.zip
            TL_안전장비-S63_DATA3_용접마스크미착용-M0/
            TL_안전장비-S63_DATA3_용접마스크미착용-M0.zip
            TL_안전장비-S63_DATA3_용접마스크착용-M1/
            TL_안전장비-S63_DATA3_용접마스크착용-M1.zip
    Validation/
        01.원천데이터/
            VS_안전장비-S63_DATA3_안전대미착용-B0/
            VS_안전장비-S63_DATA3_안전대미착용-B0.zip
            VS_안전장비-S63_DATA3_안전대착용-B1/
            VS_안전장비-S63_DATA3_안전대착용-B1.zip
            VS_안전장비-S63_DATA3_안전모미착용-H0/
            VS_안전장비-S63_DATA3_안전모미착용-H0.zip
            VS_안전장비-S63_DATA3_안전모착용-H1/
            VS_안전장비-S63_DATA3_안전모착용-H1.zip
            VS_안전장비-S63_DATA3_용접마스크미착용-M0/
            VS_안전장비-S63_DATA3_용접마스크미착용-M0.zip
            VS_안전장비-S63_DATA3_용접마스크착용-M1/
            VS_안전장비-S63_DATA3_용접마스크착용-M1.zip
        02.라벨링데이터/
            VL_안전장비-S63_DATA3_안전대미착용-B0/
            VL_안전장비-S63_DATA3_안전대미착용-B0.zip
            VL_안전장비-S63_DATA3_안전대착용-B1/
            VL_안전장비-S63_DATA3_안전대착용-B1.zip
            VL_안전장비-S63_DATA3_안전모미착용-H0/
            VL_안전장비-S63_DATA3_안전모미착용-H0.zip
            VL_안전장비-S63_DATA3_안전모착용-H1/
            VL_안전장비-S63_DATA3_안전모착용-H1.zip
            VL_안전장비-S63_DATA3_용접마스크미착용-M0/
            VL_안전장비-S63_DATA3_용접마스크미착용-M0.zip
            VL_안전장비-S63_DATA3_용접마스크착용-M1/
            VL_안전장비-S63_DATA3_용접마스크착용-M1.zip
    ppe_quality_report/
        annotation_inventory.csv
        class_summary.csv
        clean_annotations.csv
        clean_class_summary.csv
        clean_images.csv
        excluded_images.csv
        image_inventory.csv
        images_without_valid_polygon.csv
        issue_summary.csv
        quality_issues.csv

In [4]:
from collections import Counter, defaultdict
import pandas as pd

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp"}
JSON_EXTENSION = ".json"


def collect_files(root: Path):
    image_paths = []
    json_paths = []

    for path in root.rglob("*"):
        if not path.is_file():
            continue

        suffix = path.suffix.lower()

        if suffix in IMAGE_EXTENSIONS:
            image_paths.append(path)
        elif suffix == JSON_EXTENSION:
            json_paths.append(path)

    return sorted(image_paths), sorted(json_paths)


image_paths, json_paths = collect_files(DATA_ROOT)

print(f"전체 이미지 수: {len(image_paths):,}")
print(f"전체 JSON 수: {len(json_paths):,}")

print("\n이미지 확장자:")
print(Counter(path.suffix.lower() for path in image_paths))

print("\n상위 JSON 폴더:")
for folder, count in Counter(str(p.parent) for p in json_paths).most_common(20):
    print(f"{count:>8,}  {folder}")

전체 이미지 수: 76,966
전체 JSON 수: 76,966

이미지 확장자:
Counter({'.jpg': 76966})

상위 JSON 폴더:
  13,632  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전대미착용-B0
  13,559  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전모착용-H1
  13,502  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전모미착용-H0
  13,303  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전대착용-B1
   7,480  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_용접마스크미착용-M0
   6,938  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_용접마스크착용-M1
   1,704  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Validation/02.라벨링데이터/VL_안전장비-S63_DATA3_안전대미착용-B0
   1,695  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Validation/02.라벨링데이터/VL_안전장비-S63_DATA3_안전모착용-H1
   1,688  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Validation/02.라벨링데이터/VL_안전장비-S63_DATA3_안전모미착용-H0
   1,663  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Validation/02.라벨링데이터/VL_안전장비-S63_DATA3_안전대착용-B1
     935  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Validation/02.라벨링데이터/VL_안전장비-S63_DATA3_용접마스크미착용-M0
     867  /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Validation/02.라벨링데이터/VL_안전장비-S63_DATA3_용접마스크착용-M1

In [5]:
def build_unique_stem_map(paths):
    stem_map = defaultdict(list)

    for path in paths:
        stem_map[path.stem].append(path)

    return stem_map


image_stem_map = build_unique_stem_map(image_paths)
json_stem_map = build_unique_stem_map(json_paths)

duplicate_image_stems = {
    stem: paths
    for stem, paths in image_stem_map.items()
    if len(paths) > 1
}

duplicate_json_stems = {
    stem: paths
    for stem, paths in json_stem_map.items()
    if len(paths) > 1
}

image_stems = set(image_stem_map)
json_stems = set(json_stem_map)

images_without_json = sorted(image_stems - json_stems)
jsons_without_image = sorted(json_stems - image_stems)

print(f"중복 이미지 stem: {len(duplicate_image_stems):,}")
print(f"중복 JSON stem: {len(duplicate_json_stems):,}")
print(f"JSON 없는 이미지: {len(images_without_json):,}")
print(f"이미지 없는 JSON: {len(jsons_without_image):,}")

assert not duplicate_image_stems, "중복 이미지 stem이 있습니다."
assert not duplicate_json_stems, "중복 JSON stem이 있습니다."

중복 이미지 stem: 0
중복 JSON stem: 0
JSON 없는 이미지: 0
이미지 없는 JSON: 0

In [6]:
paired_records = []

for stem in sorted(image_stems & json_stems):
    image_path = image_stem_map[stem][0]
    json_path = json_stem_map[stem][0]

    paired_records.append({
        "stem": stem,
        "image_path": str(image_path),
        "json_path": str(json_path),
    })

pairs_df = pd.DataFrame(paired_records)

print("매칭 수:", len(pairs_df))
display(pairs_df.head())

매칭 수: 76966

,stem,image_path,json_path
0,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000254,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
1,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000255,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
2,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000256,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
3,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000257,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
4,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000258,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...

In [7]:
import re

KNOWN_PPE_CODES = {"B0", "B1", "H0", "H1", "M0", "M1"}

# "_B0_", "_H1_" 같은 패턴
PPE_CODE_PATTERN = re.compile(r"_(B0|B1|H0|H1|M0|M1)_")


def extract_ppe_code(filename_stem: str):
    match = PPE_CODE_PATTERN.search(filename_stem)
    return match.group(1) if match else None


pairs_df["filename_ppe_code"] = pairs_df["stem"].map(extract_ppe_code)

print("파일명 PPE 코드 통계:")
display(
    pairs_df["filename_ppe_code"]
    .value_counts(dropna=False)
    .rename_axis("code")
    .reset_index(name="count")
)

failed_code_df = pairs_df[pairs_df["filename_ppe_code"].isna()]

print("코드 판별 실패:", len(failed_code_df))
display(failed_code_df.head())

파일명 PPE 코드 통계:

  code  count
0   B0  15336
1   H1  15254
2   H0  15190
3   B1  14966
4   M0   8415
5   M1   7805

코드 판별 실패: 0

Empty DataFrame
Columns: [stem, image_path, json_path, filename_ppe_code]
Index: []

In [8]:
import json
from typing import Any


def load_json(json_path: Path):
    with json_path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)


def flatten_json_structure(
    obj: Any,
    prefix: str = "root",
    max_list_items: int = 3,
    max_depth: int = 8,
    current_depth: int = 0,
):
    rows = []

    if current_depth > max_depth:
        rows.append({
            "path": prefix,
            "type": "MAX_DEPTH_REACHED",
            "example": None,
        })
        return rows

    if isinstance(obj, dict):
        rows.append({
            "path": prefix,
            "type": "dict",
            "example": f"{len(obj)} keys",
        })

        for key, value in obj.items():
            child_prefix = f"{prefix}.{key}"
            rows.extend(
                flatten_json_structure(
                    value,
                    prefix=child_prefix,
                    max_list_items=max_list_items,
                    max_depth=max_depth,
                    current_depth=current_depth + 1,
                )
            )

    elif isinstance(obj, list):
        rows.append({
            "path": prefix,
            "type": "list",
            "example": f"length={len(obj)}",
        })

        for index, value in enumerate(obj[:max_list_items]):
            child_prefix = f"{prefix}[{index}]"
            rows.extend(
                flatten_json_structure(
                    value,
                    prefix=child_prefix,
                    max_list_items=max_list_items,
                    max_depth=max_depth,
                    current_depth=current_depth + 1,
                )
            )

    else:
        example = obj

        if isinstance(example, str) and len(example) > 150:
            example = example[:150] + "..."

        rows.append({
            "path": prefix,
            "type": type(obj).__name__,
            "example": example,
        })

    return rows

In [9]:
representative_rows = []

for code in sorted(KNOWN_PPE_CODES):
    code_rows = pairs_df[pairs_df["filename_ppe_code"] == code]

    if code_rows.empty:
        print(f"[경고] {code} 파일이 없습니다.")
        continue

    selected = code_rows.iloc[0]

    representative_rows.append({
        "code": code,
        "stem": selected["stem"],
        "image_path": selected["image_path"],
        "json_path": selected["json_path"],
    })

representative_df = pd.DataFrame(representative_rows)
display(representative_df)

,code,stem,image_path,json_path
0,B0,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000254,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
1,B1,S63_DATA3_B1_L1_D2023-08-25-10-42_001_000182,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
2,H0,S63_DATA3_H0_L1_D2023-09-07-13-08_001_000085,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
3,H1,S63_DATA3_H1_L1_D2023-09-14-10-23_001_000058,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
4,M0,S63_DATA3_M0_L1_D2023-08-25-16-49_001_000001,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
5,M1,S63_DATA3_M1_L1_D2023-10-18-14-01_022_000008,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...

In [10]:
structure_frames = []

for row in representative_rows:
    code = row["code"]
    json_path = Path(row["json_path"])

    data = load_json(json_path)
    structure = flatten_json_structure(data)

    structure_df = pd.DataFrame(structure)
    structure_df.insert(0, "code", code)
    structure_df.insert(1, "json_path", str(json_path))

    structure_frames.append(structure_df)

    print("=" * 100)
    print("PPE 코드:", code)
    print("JSON:", json_path)
    display(structure_df.head(150))

====================================================================================================
PPE 코드: B0
JSON: /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전대미착용-B0/S63_DATA3_B0_L1_D2023-08-25-10-50_001_000254.json

,code,json_path,path,type,example
0,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root,dict,5 keys
1,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info,dict,2 keys
2,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.name,str,37.S63-D3-B0
3,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.id,str,10
4,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories,list,length=1
5,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0],dict,2 keys
6,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].name,str,안전장비
7,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value,list,length=1
8,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value[0],str,안전대 미착용
9,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class,list,length=1
10,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0],dict,3 keys
11,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].id,int,0
12,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].name,str,안전대 미착용몸통
13,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints,list,length=1
14,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints[0],str,
15,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images,dict,9 keys
16,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.id,int,1164269
17,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.file_name,str,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000254.jpg
18,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.width,int,1920
19,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.height,int,1080
20,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.date,str,2023-08-25 10:50:00
21,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.location,str,한화오션에코텍
22,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.environment,str,실내
23,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.device,str,고프로
24,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.angle,int,0
25,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations,list,length=1
26,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0],dict,6 keys
27,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_id,int,1
28,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_class,int,0
29,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox,list,length=4
30,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[0],float,1404.718228
31,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[1],float,190.459519
32,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[2],float,1905.138746
33,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon,list,length=72
34,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[0],float,1397.995155
35,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[1],float,268.167779
36,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[2],float,1474.536564
37,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].keypoint,list,length=0
38,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories,list,length=1
39,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0],dict,2 keys
40,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].name,str,안전장비
41,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].value,str,안전대 미착용

====================================================================================================
PPE 코드: B1
JSON: /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전대착용-B1/S63_DATA3_B1_L1_D2023-08-25-10-42_001_000182.json

,code,json_path,path,type,example
0,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root,dict,5 keys
1,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info,dict,2 keys
2,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.name,str,38.S63-D3-B1
3,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.id,str,17
4,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories,list,length=1
5,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0],dict,2 keys
6,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].name,str,안전장비
7,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value,list,length=1
8,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value[0],str,안전대 착용
9,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class,list,length=1
10,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0],dict,3 keys
11,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].id,int,0
12,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].name,str,안전대 착용몸통
13,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints,list,length=1
14,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints[0],str,
15,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images,dict,9 keys
16,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.id,int,1193751
17,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.file_name,str,S63_DATA3_B1_L1_D2023-08-25-10-42_001_000182.jpg
18,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.width,int,1920
19,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.height,int,1080
20,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.date,str,2023-08-25 10:42:00
21,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.location,str,한화오션에코텍
22,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.environment,str,실외
23,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.device,str,고프로
24,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.angle,int,0
25,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations,list,length=2
26,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0],dict,6 keys
27,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_id,int,1
28,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_class,int,0
29,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox,list,length=4
30,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[0],float,42.37
31,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[1],float,455.94
32,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[2],float,195.52446
33,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon,list,length=0
34,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].keypoint,list,length=0
35,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories,list,length=1
36,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0],dict,2 keys
37,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].name,str,안전장비
38,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].value,str,안전대 착용
39,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1],dict,6 keys
40,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].object_id,int,2
41,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].object_class,int,0
42,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].bbox,list,length=0
43,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].polygon,list,length=90
44,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].polygon[0],float,93.776401
45,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].polygon[1],float,455.944812
46,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].polygon[2],float,79.787915
47,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].keypoint,list,length=0
48,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].categories,list,length=1
49,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].categories[0],dict,2 keys
50,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].categories[0].name,str,안전장비
51,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[1].categories[0].value,str,안전대 착용

====================================================================================================
PPE 코드: H0
JSON: /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전모미착용-H0/S63_DATA3_H0_L1_D2023-09-07-13-08_001_000085.json

,code,json_path,path,type,example
0,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root,dict,5 keys
1,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info,dict,2 keys
2,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.name,str,35.S63-D3-H0
3,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.id,str,15
4,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories,list,length=1
5,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0],dict,2 keys
6,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].name,str,안전장비
7,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value,list,length=1
8,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value[0],str,안전모 미착용
9,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class,list,length=1
10,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0],dict,3 keys
11,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].id,int,0
12,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].name,str,안전모 미착용머리
13,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints,list,length=1
14,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints[0],str,
15,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images,dict,9 keys
16,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.id,int,1161492
17,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.file_name,str,S63_DATA3_H0_L1_D2023-09-07-13-08_001_000085.jpg
18,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.width,int,1920
19,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.height,int,1080
20,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.date,str,2023-09-07 13:08:00
21,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.location,str,한화오션에코텍
22,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.environment,str,실외
23,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.device,str,고프로
24,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.angle,int,0
25,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations,list,length=1
26,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0],dict,6 keys
27,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_id,int,1
28,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_class,int,0
29,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox,list,length=4
30,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[0],float,1647.398522
31,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[1],float,462.7
32,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[2],float,1756.609782
33,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon,list,length=22
34,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[0],float,1674.85
35,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[1],float,554.77
36,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[2],float,1664.895105
37,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].keypoint,list,length=0
38,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories,list,length=1
39,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0],dict,2 keys
40,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].name,str,안전장비
41,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].value,str,안전모 미착용

====================================================================================================
PPE 코드: H1
JSON: /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_안전모착용-H1/S63_DATA3_H1_L1_D2023-09-14-10-23_001_000058.json

,code,json_path,path,type,example
0,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root,dict,5 keys
1,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info,dict,2 keys
2,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.name,str,36.S63-D3-H1
3,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.id,str,16
4,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories,list,length=1
5,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0],dict,2 keys
6,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].name,str,안전장비
7,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value,list,length=1
8,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value[0],str,안전모 착용
9,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class,list,length=1
10,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0],dict,3 keys
11,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].id,int,0
12,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].name,str,안전모 착용머리
13,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints,list,length=1
14,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints[0],str,
15,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images,dict,9 keys
16,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.id,int,1213492
17,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.file_name,str,S63_DATA3_H1_L1_D2023-09-14-10-23_001_000058.jpg
18,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.width,int,1920
19,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.height,int,1080
20,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.date,str,2023-09-14 10:23:00
21,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.location,str,한화오션에코텍
22,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.environment,str,실외
23,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.device,str,고프로
24,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.angle,int,0
25,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations,list,length=1
26,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0],dict,6 keys
27,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_id,int,1
28,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_class,int,0
29,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox,list,length=4
30,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[0],float,344.098081
31,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[1],float,3.037593
32,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[2],float,612.691744
33,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon,list,length=28
34,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[0],float,366.25
35,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[1],float,5.13
36,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[2],float,358.9
37,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].keypoint,list,length=0
38,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories,list,length=1
39,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0],dict,2 keys
40,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].name,str,안전장비
41,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].value,str,안전모 착용

====================================================================================================
PPE 코드: M0
JSON: /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_용접마스크미착용-M0/S63_DATA3_M0_L1_D2023-08-25-16-49_001_000001.json

,code,json_path,path,type,example
0,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root,dict,5 keys
1,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info,dict,2 keys
2,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.name,str,39.S63-D3-M0
3,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.id,str,18
4,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories,list,length=1
5,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0],dict,2 keys
6,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].name,str,안전장비
7,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value,list,length=1
8,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value[0],str,용접마스크 미착용
9,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class,list,length=1
10,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0],dict,3 keys
11,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].id,int,1
12,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].name,str,용접마스크 미착용머리
13,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints,list,length=1
14,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints[0],str,
15,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images,dict,9 keys
16,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.id,int,1903175
17,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.file_name,str,A63_DATA3_M0_L1_D2023-08-25-16-49_001_000001.jpg
18,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.width,int,1920
19,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.height,int,1080
20,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.date,str,2023-08-25 16:49:00
21,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.location,str,L1
22,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.environment,str,실내
23,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.device,str,고프로
24,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.angle,int,0
25,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations,list,length=1
26,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0],dict,6 keys
27,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_id,int,1
28,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_class,int,1
29,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox,list,length=4
30,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[0],float,718.151965
31,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[1],float,81.668958
32,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[2],float,855.800082
33,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon,list,length=44
34,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[0],float,718.437113
35,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[1],float,123.854323
36,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[2],float,729.487736
37,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].keypoint,list,length=0
38,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories,list,length=1
39,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0],dict,2 keys
40,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].name,str,안전장비
41,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].value,str,용접마스크 미착용

====================================================================================================
PPE 코드: M1
JSON: /content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_안전장비-S63_DATA3_용접마스크착용-M1/S63_DATA3_M1_L1_D2023-10-18-14-01_022_000008.json

,code,json_path,path,type,example
0,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root,dict,5 keys
1,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info,dict,2 keys
2,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.name,str,40.S63-D3-M1
3,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.data_info.id,str,19
4,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories,list,length=1
5,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0],dict,2 keys
6,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].name,str,안전장비
7,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value,list,length=1
8,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.categories[0].value[0],str,용접마스크 착용
9,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class,list,length=1
10,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0],dict,3 keys
11,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].id,int,1
12,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].name,str,용접마스크 착용머리
13,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints,list,length=1
14,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.class[0].keypoints[0],str,
15,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images,dict,9 keys
16,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.id,int,1493587
17,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.file_name,str,S63_DATA3_M1_L1_D2023-10-18-14-01_022_000008.jpg
18,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.width,int,1920
19,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.height,int,1080
20,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.date,str,2023-10-18 14:01:00
21,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.location,str,한화오션에코텍
22,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.environment,str,실내
23,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.device,str,디지털카메라
24,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.images.angle,int,0
25,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations,list,length=1
26,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0],dict,6 keys
27,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_id,int,1
28,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].object_class,int,1
29,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox,list,length=4
30,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[0],float,801.078074
31,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[1],float,397.97
32,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].bbox[2],float,927.707955
33,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon,list,length=22
34,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[0],float,877.265973
35,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[1],float,581.991085
36,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].polygon[2],float,910.074294
37,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].keypoint,list,length=0
38,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories,list,length=1
39,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0],dict,2 keys
40,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].name,str,안전장비
41,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,root.annotations[0].categories[0].value,str,용접마스크 착용

In [11]:
from tqdm.auto import tqdm


def collect_key_paths(
    obj,
    prefix="root",
    paths=None,
    max_depth=8,
    current_depth=0,
):
    if paths is None:
        paths = set()

    if current_depth > max_depth:
        return paths

    if isinstance(obj, dict):
        for key, value in obj.items():
            child_path = f"{prefix}.{key}"
            paths.add(child_path)

            collect_key_paths(
                value,
                prefix=child_path,
                paths=paths,
                max_depth=max_depth,
                current_depth=current_depth + 1,
            )

    elif isinstance(obj, list):
        list_path = f"{prefix}[]"
        paths.add(list_path)

        # 구조 확인 목적이므로 첫 요소 중심
        for value in obj[:1]:
            collect_key_paths(
                value,
                prefix=list_path,
                paths=paths,
                max_depth=max_depth,
                current_depth=current_depth + 1,
            )

    return paths

In [12]:
KEY_SCAN_LIMIT = min(2000, len(pairs_df))

# 코드별·폴더별 편향을 줄이기 위해 균등 간격 샘플
if KEY_SCAN_LIMIT > 0:
    sample_indices = (
        pd.Series(range(len(pairs_df)))
        .sample(n=KEY_SCAN_LIMIT, random_state=42)
        .sort_values()
        .tolist()
    )
else:
    sample_indices = []

key_path_counter = Counter()
json_load_errors = []

for idx in tqdm(sample_indices, desc="JSON 키 구조 검사"):
    json_path = Path(pairs_df.iloc[idx]["json_path"])

    try:
        data = load_json(json_path)
        key_paths = collect_key_paths(data)

        for key_path in key_paths:
            key_path_counter[key_path] += 1

    except Exception as e:
        json_load_errors.append({
            "json_path": str(json_path),
            "error": repr(e),
        })

key_paths_df = pd.DataFrame(
    [
        {
            "key_path": key_path,
            "file_count": count,
            "ratio": count / max(KEY_SCAN_LIMIT, 1),
        }
        for key_path, count in key_path_counter.most_common()
    ]
)

print("검사 JSON 수:", KEY_SCAN_LIMIT)
print("JSON 로드 오류:", len(json_load_errors))

display(key_paths_df.head(200))

JSON 키 구조 검사:   0%|          | 0/2000 [00:00<?, ?it/s]

검사 JSON 수: 2000
JSON 로드 오류: 0

                                 key_path  file_count  ratio
0                      root.images.device        2000  1.000
1                 root.categories[].value        2000  1.000
2                       root.class[].name        2000  1.000
3                 root.images.environment        2000  1.000
4                       root.categories[]        2000  1.000
5                       root.data_info.id        2000  1.000
6                         root.class[].id        2000  1.000
7                        root.annotations        2000  1.000
8                      root.annotations[]        2000  1.000
9                      root.images.height        2000  1.000
10                  root.images.file_name        2000  1.000
11              root.categories[].value[]        2000  1.000
12                            root.images        2000  1.000
13                      root.images.angle        2000  1.000
14                       root.images.date        2000  1.000
15                             root.class        2000  1.000
16               root.class[].keypoints[]        2000  1.000
17                   root.images.location        2000  1.000
18                 root.class[].keypoints        2000  1.000
19                    root.data_info.name        2000  1.000
20                        root.categories        2000  1.000
21                         root.images.id        2000  1.000
22                      root.images.width        2000  1.000
23                         root.data_info        2000  1.000
24                 root.categories[].name        2000  1.000
25                           root.class[]        2000  1.000
26                root.annotations[].bbox        1998  0.999
27          root.annotations[].keypoint[]        1998  0.999
28        root.annotations[].categories[]        1998  0.999
29              root.annotations[].bbox[]        1998  0.999
30   root.annotations[].categories[].name        1998  0.999
31           root.annotations[].object_id        1998  0.999
32        root.annotations[].object_class        1998  0.999
33            root.annotations[].keypoint        1998  0.999
34          root.annotations[].categories        1998  0.999
35             root.annotations[].polygon        1998  0.999
36  root.annotations[].categories[].value        1998  0.999
37           root.annotations[].polygon[]        1998  0.999

In [13]:
CANDIDATE_KEYWORDS = [
    "annotation",
    "annotations",
    "polygon",
    "segmentation",
    "point",
    "points",
    "bbox",
    "box",
    "class",
    "category",
    "label",
    "code",
    "person",
    "worker",
    "image",
    "file_name",
    "filename",
    "width",
    "height",
]

In [14]:
candidate_mask = key_paths_df["key_path"].str.lower().apply(
    lambda path: any(keyword in path for keyword in CANDIDATE_KEYWORDS)
)

candidate_keys_df = key_paths_df[candidate_mask].copy()

display(candidate_keys_df.head(300))

                                 key_path  file_count  ratio
0                      root.images.device        2000  1.000
2                       root.class[].name        2000  1.000
3                 root.images.environment        2000  1.000
6                         root.class[].id        2000  1.000
7                        root.annotations        2000  1.000
8                      root.annotations[]        2000  1.000
9                      root.images.height        2000  1.000
10                  root.images.file_name        2000  1.000
12                            root.images        2000  1.000
13                      root.images.angle        2000  1.000
14                       root.images.date        2000  1.000
15                             root.class        2000  1.000
16               root.class[].keypoints[]        2000  1.000
17                   root.images.location        2000  1.000
18                 root.class[].keypoints        2000  1.000
21                         root.images.id        2000  1.000
22                      root.images.width        2000  1.000
25                           root.class[]        2000  1.000
26                root.annotations[].bbox        1998  0.999
27          root.annotations[].keypoint[]        1998  0.999
28        root.annotations[].categories[]        1998  0.999
29              root.annotations[].bbox[]        1998  0.999
30   root.annotations[].categories[].name        1998  0.999
31           root.annotations[].object_id        1998  0.999
32        root.annotations[].object_class        1998  0.999
33            root.annotations[].keypoint        1998  0.999
34          root.annotations[].categories        1998  0.999
35             root.annotations[].polygon        1998  0.999
36  root.annotations[].categories[].value        1998  0.999
37           root.annotations[].polygon[]        1998  0.999

In [15]:
for row in representative_rows:
    code = row["code"]
    json_path = Path(row["json_path"])

    data = load_json(json_path)
    formatted = json.dumps(
        data,
        ensure_ascii=False,
        indent=2,
    )

    print("\n" + "=" * 120)
    print(f"[{code}] {json_path.name}")
    print("=" * 120)
    print(formatted[:15000])

    if len(formatted) > 15000:
        print("\n... 출력 생략 ...")

========================================================================================================================
[B0] S63_DATA3_B0_L1_D2023-08-25-10-50_001_000254.json
========================================================================================================================
{
  "data_info": {
    "name": "37.S63-D3-B0",
    "id": "10"
  },
  "categories": [
    {
      "name": "안전장비",
      "value": [
        "안전대 미착용"
      ]
    }
  ],
  "class": [
    {
      "id": 0,
      "name": "안전대 미착용몸통",
      "keypoints": [
        ""
      ]
    }
  ],
  "images": {
    "id": 1164269,
    "file_name": "S63_DATA3_B0_L1_D2023-08-25-10-50_001_000254.jpg",
    "width": 1920,
    "height": 1080,
    "date": "2023-08-25 10:50:00",
    "location": "한화오션에코텍",
    "environment": "실내",
    "device": "고프로",
    "angle": 0
  },
  "annotations": [
    {
      "object_id": 1,
      "object_class": 0,
      "bbox": [
        1404.7182283658417,
        190.459518599562,
        1905.1387459156142,
        878.0743982494512
      ],
      "polygon": [
        1397.9951553791,
        268.1677787683,
        1474.5365642813,
        238.3391414755,
        1542.0731015479,
        211.8873310461,
        1601.1675716563,
        196.6916101611,
        1641.35,
        195.46,
        1670.96,
        203.79,
        1715.4168805324,
        236.0879235666,
        1772.09,
        263.48,
        1826.76,
        298.92,
        1849.48,
        310.39,
        1875.8161565407,
        341.8951652844,
        1917.3,
        381.73,
        1896.57,
        417.69,
        1893.2630953346,
        453.3304517744,
        1876.16,
        559.41,
        1837.4,
        616.59,
        1839.2338655212,
        673.3870023683,
        1855.79,
        713.73,
        1854.4295864062,
        769.0637634961,
        1856.83,
        868.83,
        1809.76,
        872.56,
        1715.86,
        876.91,
        1627.18,
        878.19,
        1529.691403049,
        872.6197873049,
        1477.9133911446,
        864.7405246238,
        1426.6981837174,
        861.3636977605,
        1429.5122061035,
        798.8924007888,
        1427.8237926718,
        783.1338754266,
        1415.1494358448,
        748.8649359303,
        1441.9911572161,
        702.1836813716,
        1466.4988158594,
        636.8299249894,
        1474.6680354072,
        545.8014785999,
        1485.1713176829,
        419.7620912914,
        1469.9999099513,
        369.5797426408,
        1459.4966276756,
        308.8941117144,
        1412.8153731169,
        269.2150453395
      ],
      "keypoint": [],
      "categories": [
        {
          "name": "안전장비",
          "value": "안전대 미착용"
        }
      ]
    }
  ]
}

========================================================================================================================
[B1] S63_DATA3_B1_L1_D2023-08-25-10-42_001_000182.json
========================================================================================================================
{
  "data_info": {
    "name": "38.S63-D3-B1",
    "id": "17"
  },
  "categories": [
    {
      "name": "안전장비",
      "value": [
        "안전대 착용"
      ]
    }
  ],
  "class": [
    {
      "id": 0,
      "name": "안전대 착용몸통",
      "keypoints": [
        ""
      ]
    }
  ],
  "images": {
    "id": 1193751,
    "file_name": "S63_DATA3_B1_L1_D2023-08-25-10-42_001_000182.jpg",
    "width": 1920,
    "height": 1080,
    "date": "2023-08-25 10:42:00",
    "location": "한화오션에코텍",
    "environment": "실외",
    "device": "고프로",
    "angle": 0
  },
  "annotations": [
    {
      "object_id": 1,
      "object_class": 0,
      "bbox": [
        42.3700000000001,
        455.9399999999998,
        195.52445975344443,
        670.2269577067734
      ],
      "polygon": [],
      "keypoint": [],
      "categories": [
        {
          "name": "안전장비",
          "value": "안전대 착용"
        }
      ]
    },
    {
      "object_id": 2,
      "object_class": 0,
      "bbox": [],
      "polygon": [
        93.776401444,
        455.9448121032,
        79.7879145282,
        456.3333811842,
        89.890710634,
        471.4875753429,
        97.6620922539,
        491.3045984735,
        98.0506613349,
        513.841605171,
        98.8277994969,
        535.6014737066,
        91.444986958,
        550.3670987843,
        82.1193290142,
        563.9670166191,
        68.1308420985,
        582.6183325067,
        58.4166150736,
        602.8239247183,
        49.4795262108,
        612.9267208241,
        42.096713672,
        630.0237603878,
        42.096713672,
        646.3436617895,
        55.3080624257,
        660.7207177862,
        64.6337203695,
        668.880668487,
        79.0107763662,
        665.7721158391,
        73.5708092324,
        645.1779545465,
        61.9137368026,
        628.4694840638,
        68.1308420985,
        619.14382612,
        84.8393125811,
        624.9723623349,
        110.4848719266,
        630.0237603878,
        137.6847075961,
        629.6351913068,
        157.5017307267,
        629.2466222258,
        168.7702340755,
        631.1894676308,
        164.4959741846,
        640.1265564936,
        164.1074051036,
        649.4522144374,
        170.7130794805,
        655.6693197333,
        174.9873393714,
        650.6179216804,
        172.6559248854,
        643.2351091415,
        176.5416156954,
        627.6923459018,
        183.5358591532,
        598.5496648274,
        180.4273065053,
        584.9497469927,
        183.1472900722,
        562.0241712141,
        190.1415335301,
        539.0985954356,
        183.9244282342,
        525.1101085198,
        190.1415335301,
        524.7215394388,
        190.1415335301,
        516.561588738,
        180.0387374243,
        516.950157819,
        173.8216321284,
        497.9102728503,
        166.4388195896,
        485.8646313396,
        157.1131616457,
        477.7046806387,
        170.7130794805,
        514.618743333,
        121.7533752754,
        515.784450576,
        110.8734410076,
        480.8132332867,
        99.9935067398,
        462.161917399
      ],
      "keypoint": [],
      "categories": [
        {
          "name": "안전장비",
          "value": "안전대 착용"
        }
      ]
    }
  ]
}

========================================================================================================================
[H0] S63_DATA3_H0_L1_D2023-09-07-13-08_001_000085.json
========================================================================================================================
{
  "data_info": {
    "name": "35.S63-D3-H0",
    "id": "15"
  },
  "categories": [
    {
      "name": "안전장비",
      "value": [
        "안전모 미착용"
      ]
    }
  ],
  "class": [
    {
      "id": 0,
      "name": "안전모 미착용머리",
      "keypoints": [
        ""
      ]
    }
  ],
  "images": {
    "id": 1161492,
    "file_name": "S63_DATA3_H0_L1_D2023-09-07-13-08_001_000085.jpg",
    "width": 1920,
    "height": 1080,
    "date": "2023-09-07 13:08:00",
    "location": "한화오션에코텍",
    "environment": "실외",
    "device": "고프로",
    "angle": 0
  },
  "annotations": [
    {
      "object_id": 1,
      "object_class": 0,
      "bbox": [
        1647.3985223727282,
        462.6999999999986,
        1756.6097820503928,
        555.4163353187749
      ],
      "polygon": [
        1674.85,
        554.77,
        1664.8951048951,
        539.1285637439,
        1648.89,
        524.16,
        1645.86,
        496.94,
        1668.29,
        474.07,
        1701.0435718128,
        462.7003765465,
        1741.47,
        469.85,
        1754.93,
        498.49,
        1756.51,
        524.73,
        1736.42,
        538.38,
        1712.71,
        550.59
      ],
      "keypoint": [],
      "categories": [
        {
          "name": "안전장비",
          "value": "안전모 미착용"
        }
      ]
    }
  ]
}

========================================================================================================================
[H1] S63_DATA3_H1_L1_D2023-09-14-10-23_001_000058.json
========================================================================================================================
{
  "data_info": {
    "name": "36.S63-D3-H1",
    "id": "16"
  },
  "categories": [
    {
      "name": "안전장비",
      "value": [
        "안전모 착용"
      ]
    }
  ],
  "class": [
    {
      "id": 0,
      "name": "안전모 착용머리",
      "keypoints": [
        ""
      ]
    }
  ],
  "images": {
    "id": 1213492,
    "file_name": "S63_DATA3_H1_L1_D2023-09-14-10-23_001_000058.jpg",
    "width": 1920,
    "height": 1080,
    "date": "2023-09-14 10:23:00",
    "location": "한화오션에코텍",
    "environment": "실외",
    "device": "고프로",
    "angle": 0
  },
  "annotations": [
    {
      "object_id": 1,
      "object_class": 0,
      "bbox": [
        344.0980811561983,
        3.037593225374,
        612.6917443023906,
        97.31219022370641
      ],
      "polygon": [
        366.25,
        5.13,
        358.9,
        24.22,
        393.35,
        21.39,
        429.5126448026685,
        31.0154478882582,
        466.3971361867708,
        44.8471321572966,
        510.9658966092277,
        64.8262316570187,
        550.9240956086718,
        90.9527463874244,
        580.52,
        80.03,
        601.6402712618125,
        61.7525240416768,
        590.8822946081159,
        29.4785940805873,
        583.1980255697613,
        4.8889331578525,
        498.6710661478602,
        4.8889331578525,
        437.1969138410231,
        6.4257869655234,
        390.51,
        3.35
      ],
      "keypoint": [],
      "categories": [
        {
          "name": "안전장비",
          "value": "안전모 착용"
        }
      ]
    }
  ]
}

========================================================================================================================
[M0] S63_DATA3_M0_L1_D2023-08-25-16-49_001_000001.json
========================================================================================================================
{
  "data_info": {
    "name": "39.S63-D3-M0",
    "id": "18"
  },
  "categories": [
    {
      "name": "안전장비",
      "value": [
        "용접마스크 미착용"
      ]
    }
  ],
  "class": [
    {
      "id": 1,
      "name": "용접마스크 미착용머리",
      "keypoints": [
        ""
      ]
    }
  ],
  "images": {
    "id": 1903175,
    "file_name": "A63_DATA3_M0_L1_D2023-08-25-16-49_001_000001.jpg",
    "width": 1920,
    "height": 1080,
    "date": "2023-08-25 16:49:00",
    "location": "L1",
    "environment": "실내",
    "device": "고프로",
    "angle": 0
  },
  "annotations": [
    {
      "object_id": 1,
      "object_class": 1,
      "bbox": [
        718.1519645431828,
        81.6689581231759,
        855.8000816720369,
        265.8460162533329
      ],
      "polygon": [
        718.4371126609,
        123.8543231417,
        729.4877361487,
        100.589852641,
        758.5683242745,
        85.4679468156,
        788.8121359254,
        80.233440953,
        819.6375593387,
        97.6817938284,
        839.9939710268,
        123.8543231417,
        844.0652533644,
        153.51652303,
        844.0652533644,
        168.0568170929,
        856.2791003773,
        187.8316170185,
        844.0652533644,
        201.2086875563,
        821.3823946263,
        199.4638522688,
        825.4536769639,
        208.769640469,
        816.1478887636,
        226.7996051071,
        807.4237123259,
        248.3192403202,
        799.2811476507,
        258.2066402829,
        789.9753594504,
        266.3492049582,
        763.2212183746,
        257.6250285204,
        747.5177007867,
        245.4111815076,
        736.4670772989,
        230.2892756822,
        727.7429008612,
        208.1880287065,
        722.5083949985,
        180.8522758683,
        717.8555008984,
        155.8429700801
      ],
      "keypoint": [],
      "categories": [
        {
          "name": "안전장비",
          "value": "용접마스크 미착용"
        }
      ]
    }
  ]
}

========================================================================================================================
[M1] S63_DATA3_M1_L1_D2023-10-18-14-01_022_000008.json
========================================================================================================================
{
  "data_info": {
    "name": "40.S63-D3-M1",
    "id": "19"
  },
  "categories": [
    {
      "name": "안전장비",
      "value": [
        "용접마스크 착용"
      ]
    }
  ],
  "class": [
    {
      "id": 1,
      "name": "용접마스크 착용머리",
      "keypoints": [
        ""
      ]
    }
  ],
  "images": {
    "id": 1493587,
    "file_name": "S63_DATA3_M1_L1_D2023-10-18-14-01_022_000008.jpg",
    "width": 1920,
    "height": 1080,
    "date": "2023-10-18 14:01:00",
    "location": "한화오션에코텍",
    "environment": "실내",
    "device": "디지털카메라",
    "angle": 0
  },
  "annotations": [
    {
      "object_id": 1,
      "object_class": 1,
      "bbox": [
        801.0780737914587,
        397.969999999999,
        927.7079553779113,
        582.9734789985134
      ],
      "polygon": [
        877.2659732541,
        581.9910846954,
        910.0742942051,
        534.9182763744,
        925.765230312,
        497.8306092125,
        928.6,
        449.99,
        911.34,
        409.11,
        867.03,
        397.48,
        820.83,
        419.88,
        801.7,
        477.01,
        811.32,
        531.62,
        814.07,
        574.23,
        852.66,
        579.72
      ],
      "keypoint": [],
      "categories": [
        {
          "name": "안전장비",
          "value": "용접마스크 착용"
        }
      ]
    }
  ]
}

In [16]:
def find_lists(obj, prefix="root", result=None):
    if result is None:
        result = []

    if isinstance(obj, dict):
        for key, value in obj.items():
            find_lists(
                value,
                prefix=f"{prefix}.{key}",
                result=result,
            )

    elif isinstance(obj, list):
        item_types = Counter(type(item).__name__ for item in obj)

        sample_keys = None
        if obj and isinstance(obj[0], dict):
            sample_keys = sorted(obj[0].keys())

        result.append({
            "path": prefix,
            "length": len(obj),
            "item_types": dict(item_types),
            "first_item_keys": sample_keys,
        })

        for index, item in enumerate(obj[:2]):
            find_lists(
                item,
                prefix=f"{prefix}[{index}]",
                result=result,
            )

    return result

In [17]:
list_analysis_rows = []

for row in representative_rows:
    code = row["code"]
    json_path = Path(row["json_path"])
    data = load_json(json_path)

    list_rows = find_lists(data)

    for list_row in list_rows:
        list_row["code"] = code
        list_row["json_path"] = str(json_path)
        list_analysis_rows.append(list_row)

list_analysis_df = pd.DataFrame(list_analysis_rows)

columns = [
    "code",
    "path",
    "length",
    "item_types",
    "first_item_keys",
    "json_path",
]

display(
    list_analysis_df[columns]
    .sort_values(["code", "length"], ascending=[True, False])
    .head(200)
)

,code,path,length,item_types,first_item_keys,json_path
6,B0,root.annotations[0].polygon,72,{'float': 72},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
5,B0,root.annotations[0].bbox,4,{'float': 4},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
0,B0,root.categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
1,B0,root.categories[0].value,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
2,B0,root.class,1,{'dict': 1},"[id, keypoints, name]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
3,B0,root.class[0].keypoints,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
4,B0,root.annotations,1,{'dict': 1},"[bbox, categories, keypoint, object_class, obj...",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
8,B0,root.annotations[0].categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
7,B0,root.annotations[0].keypoint,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
19,B1,root.annotations[1].polygon,90,{'float': 90},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
14,B1,root.annotations[0].bbox,4,{'float': 4},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
13,B1,root.annotations,2,{'dict': 2},"[bbox, categories, keypoint, object_class, obj...",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
9,B1,root.categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
10,B1,root.categories[0].value,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
11,B1,root.class,1,{'dict': 1},"[id, keypoints, name]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
12,B1,root.class[0].keypoints,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
17,B1,root.annotations[0].categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
21,B1,root.annotations[1].categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
15,B1,root.annotations[0].polygon,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
16,B1,root.annotations[0].keypoint,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
18,B1,root.annotations[1].bbox,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
20,B1,root.annotations[1].keypoint,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
28,H0,root.annotations[0].polygon,22,{'float': 22},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
27,H0,root.annotations[0].bbox,4,{'float': 4},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
22,H0,root.categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
23,H0,root.categories[0].value,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
24,H0,root.class,1,{'dict': 1},"[id, keypoints, name]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
25,H0,root.class[0].keypoints,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
26,H0,root.annotations,1,{'dict': 1},"[bbox, categories, keypoint, object_class, obj...",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
30,H0,root.annotations[0].categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
29,H0,root.annotations[0].keypoint,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
37,H1,root.annotations[0].polygon,28,{'float': 28},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
36,H1,root.annotations[0].bbox,4,{'float': 4},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
31,H1,root.categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
32,H1,root.categories[0].value,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
33,H1,root.class,1,{'dict': 1},"[id, keypoints, name]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
34,H1,root.class[0].keypoints,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
35,H1,root.annotations,1,{'dict': 1},"[bbox, categories, keypoint, object_class, obj...",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
39,H1,root.annotations[0].categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
38,H1,root.annotations[0].keypoint,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
46,M0,root.annotations[0].polygon,44,{'float': 44},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
45,M0,root.annotations[0].bbox,4,{'float': 4},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
40,M0,root.categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
41,M0,root.categories[0].value,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
42,M0,root.class,1,{'dict': 1},"[id, keypoints, name]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
43,M0,root.class[0].keypoints,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
44,M0,root.annotations,1,{'dict': 1},"[bbox, categories, keypoint, object_class, obj...",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
48,M0,root.annotations[0].categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
47,M0,root.annotations[0].keypoint,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
55,M1,root.annotations[0].polygon,22,{'float': 22},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
54,M1,root.annotations[0].bbox,4,{'float': 4},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
49,M1,root.categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
50,M1,root.categories[0].value,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
51,M1,root.class,1,{'dict': 1},"[id, keypoints, name]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
52,M1,root.class[0].keypoints,1,{'str': 1},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
53,M1,root.annotations,1,{'dict': 1},"[bbox, categories, keypoint, object_class, obj...",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
57,M1,root.annotations[0].categories,1,{'dict': 1},"[name, value]",/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
56,M1,root.annotations[0].keypoint,0,{},None,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...

In [18]:
def is_number(value):
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def describe_numeric_list(value):
    if not isinstance(value, list):
        return None

    if not value:
        return {
            "structure": "empty_list",
            "length": 0,
        }

    # [x1, y1, x2, y2, ...]
    if all(is_number(item) for item in value):
        return {
            "structure": "flat_numeric_list",
            "length": len(value),
            "sample": value[:10],
        }

    # [[x1, y1], [x2, y2], ...]
    if all(
        isinstance(item, list)
        and len(item) >= 2
        and is_number(item[0])
        and is_number(item[1])
        for item in value
    ):
        return {
            "structure": "point_pair_list",
            "length": len(value),
            "sample": value[:5],
        }

    return None


def find_numeric_lists(obj, prefix="root", result=None):
    if result is None:
        result = []

    if isinstance(obj, dict):
        for key, value in obj.items():
            description = describe_numeric_list(value)

            if description is not None:
                result.append({
                    "path": f"{prefix}.{key}",
                    **description,
                })

            find_numeric_lists(
                value,
                prefix=f"{prefix}.{key}",
                result=result,
            )

    elif isinstance(obj, list):
        for index, value in enumerate(obj[:20]):
            find_numeric_lists(
                value,
                prefix=f"{prefix}[{index}]",
                result=result,
            )

    return result

In [19]:
numeric_list_rows = []

for row in representative_rows:
    code = row["code"]
    json_path = Path(row["json_path"])
    data = load_json(json_path)

    findings = find_numeric_lists(data)

    for finding in findings:
        finding["code"] = code
        finding["json_path"] = str(json_path)
        numeric_list_rows.append(finding)

numeric_lists_df = pd.DataFrame(numeric_list_rows)

display(numeric_lists_df.head(300))

,path,structure,length,sample,code,json_path
0,root.annotations[0].bbox,flat_numeric_list,4,"[1404.7182283658417, 190.459518599562, 1905.13...",B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
1,root.annotations[0].polygon,flat_numeric_list,72,"[1397.9951553791, 268.1677787683, 1474.5365642...",B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
2,root.annotations[0].keypoint,empty_list,0,NaN,B0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
3,root.annotations[0].bbox,flat_numeric_list,4,"[42.3700000000001, 455.9399999999998, 195.5244...",B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
4,root.annotations[0].polygon,empty_list,0,NaN,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
5,root.annotations[0].keypoint,empty_list,0,NaN,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
6,root.annotations[1].bbox,empty_list,0,NaN,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
7,root.annotations[1].polygon,flat_numeric_list,90,"[93.776401444, 455.9448121032, 79.7879145282, ...",B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
8,root.annotations[1].keypoint,empty_list,0,NaN,B1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
9,root.annotations[0].bbox,flat_numeric_list,4,"[1647.3985223727282, 462.6999999999986, 1756.6...",H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
10,root.annotations[0].polygon,flat_numeric_list,22,"[1674.85, 554.77, 1664.8951048951, 539.1285637...",H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
11,root.annotations[0].keypoint,empty_list,0,NaN,H0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
12,root.annotations[0].bbox,flat_numeric_list,4,"[344.0980811561983, 3.037593225374, 612.691744...",H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
13,root.annotations[0].polygon,flat_numeric_list,28,"[366.25, 5.13, 358.9, 24.22, 393.35, 21.39, 42...",H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
14,root.annotations[0].keypoint,empty_list,0,NaN,H1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
15,root.annotations[0].bbox,flat_numeric_list,4,"[718.1519645431828, 81.6689581231759, 855.8000...",M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
16,root.annotations[0].polygon,flat_numeric_list,44,"[718.4371126609, 123.8543231417, 729.487736148...",M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
17,root.annotations[0].keypoint,empty_list,0,NaN,M0,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
18,root.annotations[0].bbox,flat_numeric_list,4,"[801.0780737914587, 397.969999999999, 927.7079...",M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
19,root.annotations[0].polygon,flat_numeric_list,22,"[877.2659732541, 581.9910846954, 910.074294205...",M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
20,root.annotations[0].keypoint,empty_list,0,NaN,M1,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...

In [20]:
from PIL import Image


image_size_rows = []

for row in representative_rows:
    image_path = Path(row["image_path"])

    with Image.open(image_path) as image:
        width, height = image.size

    image_size_rows.append({
        "code": row["code"],
        "stem": row["stem"],
        "actual_width": width,
        "actual_height": height,
        "image_path": str(image_path),
        "json_path": row["json_path"],
    })

image_sizes_df = pd.DataFrame(image_size_rows)
display(image_sizes_df)

,code,stem,actual_width,actual_height,image_path,json_path
0,B0,S63_DATA3_B0_L1_D2023-08-25-10-50_001_000254,1920,1080,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
1,B1,S63_DATA3_B1_L1_D2023-08-25-10-42_001_000182,1920,1080,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
2,H0,S63_DATA3_H0_L1_D2023-09-07-13-08_001_000085,1920,1080,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
3,H1,S63_DATA3_H1_L1_D2023-09-14-10-23_001_000058,1920,1080,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
4,M0,S63_DATA3_M0_L1_D2023-08-25-16-49_001_000001,1920,1080,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...
5,M1,S63_DATA3_M1_L1_D2023-10-18-14-01_022_000008,1920,1080,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...,/content/drive/MyDrive/빅프/081_스마트야드_압축해제/3.개방데...

In [21]:
pairs_output_path = REPORT_ROOT / "image_json_pairs.csv"
representative_output_path = REPORT_ROOT / "representative_json_files.csv"
key_paths_output_path = REPORT_ROOT / "json_key_paths.csv"
candidate_keys_output_path = REPORT_ROOT / "candidate_annotation_keys.csv"
list_analysis_output_path = REPORT_ROOT / "json_list_analysis.csv"
numeric_lists_output_path = REPORT_ROOT / "numeric_coordinate_candidates.csv"
json_errors_output_path = REPORT_ROOT / "json_load_errors.csv"

pairs_df.to_csv(
    pairs_output_path,
    index=False,
    encoding="utf-8-sig",
)

representative_df.to_csv(
    representative_output_path,
    index=False,
    encoding="utf-8-sig",
)

key_paths_df.to_csv(
    key_paths_output_path,
    index=False,
    encoding="utf-8-sig",
)

candidate_keys_df.to_csv(
    candidate_keys_output_path,
    index=False,
    encoding="utf-8-sig",
)

list_analysis_df.to_csv(
    list_analysis_output_path,
    index=False,
    encoding="utf-8-sig",
)

numeric_lists_df.to_csv(
    numeric_lists_output_path,
    index=False,
    encoding="utf-8-sig",
)

pd.DataFrame(json_load_errors).to_csv(
    json_errors_output_path,
    index=False,
    encoding="utf-8-sig",
)

print("저장 완료")
print("pairs:", pairs_output_path)
print("representative:", representative_output_path)
print("key paths:", key_paths_output_path)
print("candidate keys:", candidate_keys_output_path)
print("list analysis:", list_analysis_output_path)
print("numeric lists:", numeric_lists_output_path)
print("errors:", json_errors_output_path)

저장 완료
pairs: /content/drive/MyDrive/빅프/shared_backbone_workspace/reports/image_json_pairs.csv
representative: /content/drive/MyDrive/빅프/shared_backbone_workspace/reports/representative_json_files.csv
key paths: /content/drive/MyDrive/빅프/shared_backbone_workspace/reports/json_key_paths.csv
candidate keys: /content/drive/MyDrive/빅프/shared_backbone_workspace/reports/candidate_annotation_keys.csv
list analysis: /content/drive/MyDrive/빅프/shared_backbone_workspace/reports/json_list_analysis.csv
numeric lists: /content/drive/MyDrive/빅프/shared_backbone_workspace/reports/numeric_coordinate_candidates.csv
errors: /content/drive/MyDrive/빅프/shared_backbone_workspace/reports/json_load_errors.csv

In [22]:
print("=" * 80)
print("1. 파일 매칭")
print("=" * 80)
print(f"이미지: {len(image_paths):,}")
print(f"JSON: {len(json_paths):,}")
print(f"매칭: {len(pairs_df):,}")
print(f"JSON 없는 이미지: {len(images_without_json):,}")
print(f"이미지 없는 JSON: {len(jsons_without_image):,}")

print("\n" + "=" * 80)
print("2. PPE 코드")
print("=" * 80)
print(
    pairs_df["filename_ppe_code"]
    .value_counts(dropna=False)
    .to_string()
)

print("\n" + "=" * 80)
print("3. annotation 관련 후보 키")
print("=" * 80)
print(
    candidate_keys_df[
        candidate_keys_df["key_path"].str.lower().str.contains(
            "annot|polygon|segment|bbox|class|category|label|point",
            regex=True,
        )
    ]
    .head(100)
    .to_string(index=False)
)

print("\n" + "=" * 80)
print("4. 가장 큰 list 후보")
print("=" * 80)

if not list_analysis_df.empty:
    print(
        list_analysis_df[
            ["code", "path", "length", "first_item_keys"]
        ]
        .sort_values("length", ascending=False)
        .head(30)
        .to_string(index=False)
    )

print("\n" + "=" * 80)
print("5. 좌표 배열 후보")
print("=" * 80)

if not numeric_lists_df.empty:
    print(
        numeric_lists_df[
            ["code", "path", "structure", "length", "sample"]
        ]
        .head(50)
        .to_string(index=False)
    )

================================================================================
1. 파일 매칭
================================================================================
이미지: 76,966
JSON: 76,966
매칭: 76,966
JSON 없는 이미지: 0
이미지 없는 JSON: 0

================================================================================
2. PPE 코드
================================================================================
filename_ppe_code
B0    15336
H1    15254
H0    15190
B1    14966
M0     8415
M1     7805

================================================================================
3. annotation 관련 후보 키
================================================================================
                             key_path  file_count  ratio
                    root.class[].name        2000  1.000
                      root.class[].id        2000  1.000
                     root.annotations        2000  1.000
                   root.annotations[]        2000  1.000
                           root.class        2000  1.000
             root.class[].keypoints[]        2000  1.000
               root.class[].keypoints        2000  1.000
                         root.class[]        2000  1.000
              root.annotations[].bbox        1998  0.999
        root.annotations[].keypoint[]        1998  0.999
      root.annotations[].categories[]        1998  0.999
            root.annotations[].bbox[]        1998  0.999
 root.annotations[].categories[].name        1998  0.999
         root.annotations[].object_id        1998  0.999
      root.annotations[].object_class        1998  0.999
          root.annotations[].keypoint        1998  0.999
        root.annotations[].categories        1998  0.999
           root.annotations[].polygon        1998  0.999
root.annotations[].categories[].value        1998  0.999
         root.annotations[].polygon[]        1998  0.999

================================================================================
4. 가장 큰 list 후보
================================================================================
code                           path  length                                                first_item_keys
  B1    root.annotations[1].polygon      90                                                           None
  B0    root.annotations[0].polygon      72                                                           None
  M0    root.annotations[0].polygon      44                                                           None
  H1    root.annotations[0].polygon      28                                                           None
  H0    root.annotations[0].polygon      22                                                           None
  M1    root.annotations[0].polygon      22                                                           None
  B1       root.annotations[0].bbox       4                                                           None
  B0       root.annotations[0].bbox       4                                                           None
  M1       root.annotations[0].bbox       4                                                           None
  M0       root.annotations[0].bbox       4                                                           None
  H0       root.annotations[0].bbox       4                                                           None
  H1       root.annotations[0].bbox       4                                                           None
  B1               root.annotations       2 [bbox, categories, keypoint, object_class, object_id, polygon]
  B1                     root.class       1                                          [id, keypoints, name]
  B1        root.class[0].keypoints       1                                                           None
  B1 root.annotations[0].categories       1                                                  [name, value]
  B1 root.annotations[1].categories       1                                                  [name, value]
  B1       root.categories[0].value       1                                                           None
  H0                     root.class       1                                          [id, keypoints, name]
  B1                root.categories       1                                                  [name, value]
  B0 root.annotations[0].categories       1                                                  [name, value]
  B0       root.categories[0].value       1                                                           None
  B0               root.annotations       1 [bbox, categories, keypoint, object_class, object_id, polygon]
  B0                root.categories       1                                                  [name, value]
  B0        root.class[0].keypoints       1                                                           None
  B0                     root.class       1                                          [id, keypoints, name]
  M1               root.annotations       1 [bbox, categories, keypoint, object_class, object_id, polygon]
  M1                root.categories       1                                                  [name, value]
  M0                root.categories       1                                                  [name, value]
  M0       root.categories[0].value       1                                                           None

================================================================================
5. 좌표 배열 후보
================================================================================
code                         path         structure  length                                                                                                                                                      sample
  B0     root.annotations[0].bbox flat_numeric_list       4                                                                               [1404.7182283658417, 190.459518599562, 1905.1387459156142, 878.0743982494512]
  B0  root.annotations[0].polygon flat_numeric_list      72       [1397.9951553791, 268.1677787683, 1474.5365642813, 238.3391414755, 1542.0731015479, 211.8873310461, 1601.1675716563, 196.6916101611, 1641.35, 195.46]
  B0 root.annotations[0].keypoint        empty_list       0                                                                                                                                                         NaN
  B1     root.annotations[0].bbox flat_numeric_list       4                                                                                [42.3700000000001, 455.9399999999998, 195.52445975344443, 670.2269577067734]
  B1  root.annotations[0].polygon        empty_list       0                                                                                                                                                         NaN
  B1 root.annotations[0].keypoint        empty_list       0                                                                                                                                                         NaN
  B1     root.annotations[1].bbox        empty_list       0                                                                                                                                                         NaN
  B1  root.annotations[1].polygon flat_numeric_list      90    [93.776401444, 455.9448121032, 79.7879145282, 456.3333811842, 89.890710634, 471.4875753429, 97.6620922539, 491.3045984735, 98.0506613349, 513.841605171]
  B1 root.annotations[1].keypoint        empty_list       0                                                                                                                                                         NaN
  H0     root.annotations[0].bbox flat_numeric_list       4                                                                              [1647.3985223727282, 462.6999999999986, 1756.6097820503928, 555.4163353187749]
  H0  root.annotations[0].polygon flat_numeric_list      22                                                       [1674.85, 554.77, 1664.8951048951, 539.1285637439, 1648.89, 524.16, 1645.86, 496.94, 1668.29, 474.07]
  H0 root.annotations[0].keypoint        empty_list       0                                                                                                                                                         NaN
  H1     root.annotations[0].bbox flat_numeric_list       4                                                                                   [344.0980811561983, 3.037593225374, 612.6917443023906, 97.31219022370641]
  H1  root.annotations[0].polygon flat_numeric_list      28                                       [366.25, 5.13, 358.9, 24.22, 393.35, 21.39, 429.5126448026685, 31.0154478882582, 466.3971361867708, 44.8471321572966]
  H1 root.annotations[0].keypoint        empty_list       0                                                                                                                                                         NaN
  M0     root.annotations[0].bbox flat_numeric_list       4                                                                                 [718.1519645431828, 81.6689581231759, 855.8000816720369, 265.8460162533329]
  M0  root.annotations[0].polygon flat_numeric_list      44 [718.4371126609, 123.8543231417, 729.4877361487, 100.589852641, 758.5683242745, 85.4679468156, 788.8121359254, 80.233440953, 819.6375593387, 97.6817938284]
  M0 root.annotations[0].keypoint        empty_list       0                                                                                                                                                         NaN
  M1     root.annotations[0].bbox flat_numeric_list       4                                                                                 [801.0780737914587, 397.969999999999, 927.7079553779113, 582.9734789985134]
  M1  root.annotations[0].polygon flat_numeric_list      22                              [877.2659732541, 581.9910846954, 910.0742942051, 534.9182763744, 925.765230312, 497.8306092125, 928.6, 449.99, 911.34, 409.11]
  M1 root.annotations[0].keypoint        empty_list       0                                                                                                                                                         NaN